# Generated by Django 3.2.9 on 2021-12-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_portfolio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='https://paradox-portfolio-bucket.s3.amazonaws.com/avatar/photo.webp', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, default='https://paradox-portfolio-bucket.s3.amazonaws.com/cv/Resume_raviraj_dnyanoba_kukade_hrGgJKC.pdf', null=True, upload_to='cv'),
        ),
    ]
